#!/usr/bin/env bash

GITCONFIG_DIR=$(cd $(dirname $(readlink -f $0)); pwd -P)
function help(){
cat<<HELP
install gitconfig file with updated name and email
Usage: $(basename $0) [options]
            Without options the installation is interactive
Options:
    -n/--name   : Name of the commiter
    -e/--email  : Email of the commiter
    -c/--copy   : Copy git_template and global git ignore to home directory
    -l/--link   : link git_template and global git ignore to home directory
                    (Not compatible with -c option)
HELP
}

function backup(){
    if [ -e $1 ]; then
        mv $1 $1_bak
        if [ $? -eq 0 ];then
            echo "$1 backed up to $1_bak"
        else
            exit 1
        fi
    fi
}

NAME=""
EMAIL=""
DO_COPY=0
DO_LINK=0

while [[ $# -gt 0 ]];do
    key="$1"

    case ${key} in
        -n|--name)
            shift
            NAME=$1
            shift
            ;;
        -e|--email)
            shift
            EMAIL=$1
            shift
            ;;
        -c|--copy)
            shift
            DO_COPY=1
            ;;
        -l|--link)
            shift
            DO_LINK=1
            ;;
        *)
            help
            exit 1;
            ;;
    esac
done

if [ $DO_LINK -eq 1 ] && [ $DO_COPY -eq 1 ]; then
    echo "Copy and link options can't be active at the same time"
    exit 1
fi

if [[ "$NAME" == "" ]];then
    echo "What is your name?"
    read NAME
fi

if [[ "$EMAIL" == "" ]];then
    echo "What is your email?"
    read EMAIL
fi

echo "Using name: $NAME and email $EMAIL"
if [ $DO_COPY -eq 1 ];then
    backup $HOME/.gitignore_global
    backup $HOME/.git_template
    cp ${GITCONFIG_DIR}/gitignore_global $HOME/.gitignore_global
    cp -r ${GITCONFIG_DIR}/git_template $HOME/.git_template
elif [ $DO_LINK -eq 1 ];then
    backup $HOME/.gitignore_global
    backup $HOME/.git_template
    ln -sf ${GITCONFIG_DIR}/gitignore_global $HOME/.gitignore_global
    ln -sf ${GITCONFIG_DIR}/git_template $HOME/.git_template
else
    echo "Ignoring git_template and gitignore global"
fi

cat ${GITCONFIG_DIR}/gitconfig | sed "s/NAME/$NAME/" > ${GITCONFIG_DIR}/.gitconfig
sed -i "s/EMAIL/$EMAIL/" ${GITCONFIG_DIR}/.gitconfig
backup $HOME/.gitconfig

mv ${GITCONFIG_DIR}/.gitconfig $HOME/.gitconfig
exit $?

