#!/usr/bin/env bash

GITCONFIG_DIR=$(cd $(dirname $(readlink -f $0)); pwd -P)
function help(){
cat<<HELP
install gitconfig file with updated name and email
Usage: $(basename $0) [options]
            Without options the installation is interactive
Options:
    -n/--name      : Name of the author
    -e/--email     : Email of the author
    --ignore-update: ignore updating the gitconfig name and email.
                        Overrules -e and -n flags
    -c/--copy      : Copy git_template and global git ignore to home directory
    -l/--link      : link git_template and global git ignore to home directory
                          (Not compatible with -c option)
HELP
}

# Logging stuff.
MARK_OK="\033[1;32m✔\033[0m"
MARK_NOK="\033[1;31m✖\033[0m"
MARK_DO="\033[1;34m➜\033[0m"

function e_header()   { printf "\n\033[1m$@\033[0m\n"; }
function e_success()  { printf " %b $@\n" $MARK_OK; }
function e_error()    { printf " %b $@\n" $MARK_NOK; }
function e_arrow()    { printf " %b $@\n" $MARK_DO; }

function backup(){
    if [ -e $1 ]; then
        mv $1 $1_bak
        if [ $? -eq 0 ];then
            e_success "$1 backed up to $1_bak"
        else
            exit 1
        fi
    fi
}

NAME=""
EMAIL=""
DO_COPY=0
DO_LINK=0
IGNORE_UPDATE=0

while [[ $# -gt 0 ]];do
    key="$1"

    case ${key} in
        -n|--name)
            shift
            NAME=$1
            shift
            ;;
        --ignore-update)
            shift
            IGNORE_UPDATE=1
            ;;
        -e|--email)
            shift
            EMAIL=$1
            shift
            ;;
        -c|--copy)
            shift
            DO_COPY=1
            ;;
        -l|--link)
            shift
            DO_LINK=1
            ;;
        *)
            help
            exit 1;
            ;;
    esac
done

if [ $DO_LINK -eq 1 ] && [ $DO_COPY -eq 1 ]; then
    e_error "Copy and link options can't be active at the same time"
    exit 1
fi


if [ $DO_COPY -eq 1 ];then
    e_arrow "Copying global ignore and templates"
    backup $HOME/.gitignore_global
    backup $HOME/.git_template
    cp ${GITCONFIG_DIR}/gitignore_global $HOME/.gitignore_global
    cp -r ${GITCONFIG_DIR}/git_template $HOME/.git_template
elif [ $DO_LINK -eq 1 ];then
    e_arrow "Linking global ignore and templates"
    backup $HOME/.gitignore_global
    backup $HOME/.git_template
    ln -sf ${GITCONFIG_DIR}/gitignore_global $HOME/.gitignore_global
    ln -sf ${GITCONFIG_DIR}/git_template $HOME/.git_template
else
    e_error "Ignoring git_template and gitignore global"
fi

if [ $IGNORE_UPDATE -eq 0 ];then
    if [[ "$NAME" == "" ]];then
        e_header "What is your name?"
        read NAME
    fi

    if [[ "$EMAIL" == "" ]];then
        e_header "What is your email?"
        read EMAIL
    fi

    e_header "Using name: $NAME and email $EMAIL"
    cat ${GITCONFIG_DIR}/gitconfig | sed "s/NAME/$NAME/" > ${GITCONFIG_DIR}/.gitconfig
    sed -i "s/EMAIL/$EMAIL/" ${GITCONFIG_DIR}/.gitconfig
else
    e_header "Please update the name and email in ~/.gitconfig"
fi

backup $HOME/.gitconfig
mv ${GITCONFIG_DIR}/.gitconfig $HOME/.gitconfig

exit $?

