#!/usr/bin/env bash

function help(){
cat<<HELP
install gitconfig file with updated name and email
Usage: $(basename $0) [options]
            Without options the installation is interactive
Options:
    -n/--name   : Name of the commiter
    -e/--email  : Email of the commiter
    -c/--copy   : Copy git_template and global git ignore to home directory
HELP
}

function backup(){
    if [ -e $1 ]; then
        mv $1 $1_bak
        if [ $? -eq 0 ];then
            echo "Existing $1 backed up to $1_bak"
        else
            exit 1
        fi
    fi
}

NAME=""
EMAIL=""
DO_COPY=0

while [[ $# -gt 0 ]];do
    key="$1"

    case ${key} in
        -n|--name)
            shift
            NAME=$1
            shift
            ;;
        -e|--email)
            shift
            EMAIL=$1
            shift
            ;;
        -c|--copy)
            shift
            DO_COPY=1
            ;;
        *)
            help
            exit 1;
            ;;
    esac
done

if [[ "$NAME" == "" ]];then
    echo "What is your name?"
    read NAME
fi

if [[ "$EMAIL" == "" ]];then
    echo "What is your email?"
    read EMAIL
fi

echo "Using name: $NAME and email $EMAIL"
if [ $DO_COPY -eq 1 ];then
    backup $HOME/.gitignore_global
    backup $HOME/.git_template
    cp gitignore_global $HOME/.gitignore_global
    cp -r ./git_template $HOME/.git_template
else
    echo "Ignoring git_template and gitignore global"
fi

cat ./gitconfig | sed "s/NAME/$NAME/" > .gitconfig
sed -i "s/EMAIL/$EMAIL/" ./.gitconfig
backup $HOME/.gitconfig

mv .gitconfig $HOME/.gitconfig
exit $?

